spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  druid:
    one:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
#      password: root
      password: bSPDA5Vr0SATCI4W4wsCyZnqjDNFOvKoYRQoV2/qwh5k9UH7hTG8wqxpQalIY+H+fHV3hFiOEZR8UdiOPiHWpA==
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      # 合并多个数据源监控
      use-global-data-source-stat: true
      filters: stat,wall,config
      remove-abandoned: true
      remove-abandoned-timeout: 18000 # s
      log-abandoned: true #关闭abanded 连接时输出错误日志
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ3wlXUyuC+xmYeIxFqAr4mcfYM852d7VvKemZHISO3VBzy3sjpNljPnSDQ60WSwBSc1M7U7Q5HnKjRXX6VSDjUCAwEAAQ==
    two:
      url: jdbc:db2://localhost:50001/demo
      username: demo
      password: wxh_zy
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
#      validation-query: select 1 from sysibm.sysdummy1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      # Global 数据源监控
      use-global-data-source-stat: true
      filters: stat,wall,slf4j
      remove-abandoned: true
      remove-abandoned-timeout: 18000 # s
      log-abandoned: true #关闭abanded 连接时输出错误日志
    stat-view-servlet:
      login-password: admin1
      login-username: admin1
      reset-enable: false
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 100
        merge-sql: true
      wall:
        enabled: true
        config:
          select-all-column-allow: false
          truncate-allow: false
          delete-where-none-check: true
        throw-exception: false
        log-violation: true
      slf4j:
        enabled: true
        statement-create-after-log-enabled: false
        statement-log-enabled: false
        statement-executable-sql-log-enable: true
        statement-log-error-enabled: true
        result-set-log-enabled: false
    web-stat-filter:
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      url-pattern: "/*"
      profile-enable: true
      principal-session-name: druid-user
    aop-patterns: com.example.pool.druid.mapper.*


mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.pool.druid.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    druid.sql.Statement: debug
    com.example.pool.druid.mapper.db2: debug
#debug: true