spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  druid:
    one:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: bSPDA5Vr0SATCI4W4wsCyZnqjDNFOvKoYRQoV2/qwh5k9UH7hTG8wqxpQalIY+H+fHV3hFiOEZR8UdiOPiHWpA==
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      # 合并多个数据源监控
      use-global-data-source-stat: true
      filters: stat,wall,config
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ3wlXUyuC+xmYeIxFqAr4mcfYM852d7VvKemZHISO3VBzy3sjpNljPnSDQ60WSwBSc1M7U7Q5HnKjRXX6VSDjUCAwEAAQ==
    two:
      url: jdbc:db2://localhost:50001/demo
      username: demo
      password: wxh_zy
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000

      # Global 数据源监控
      use-global-data-source-stat: true
      filters: stat,wall,slf4j

    stat-view-servlet:
      login-password: admin1
      login-username: admin1
      reset-enable: false
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 100
        merge-sql: true
      slf4j:
        enabled: true
        statement-create-after-log-enabled: false
        statement-log-enabled: false
        statement-executable-sql-log-enable: true
        statement-log-error-enabled: true
        result-set-log-enabled: false
    web-stat-filter:
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      url-pattern: "/*"
      profile-enable: true
  dynmicds:
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    druid.sql.Statement: debug
    com.example.pool.druid.mapper.db2: debug  # Sql日志
    org.springframework.orm.jpa: debug # 事物日志
#debug: true
